### ISSUE TITLE
Neo2 Layout support 

### ISSUE THREAD

**Issue by GoogleCodeExporter** [klausw/hackerskeyboard#446]
```
Although the ergonomical factor may not really work on the touchscreen,  it 
certainly is a hacker layout, if not THE hacker layout  per se. 
Would be nice to see the at least the first four layers working, especially if 
a keyboard is connected via OTG. 

```

Original issue reported on code.google.com by `Justus.M...@gmail.com` on 24 Dec 2014 at 1:28

**Comment by TPS** [comment]
#491 adds this. :smile:

**Comment by klausw** [comment]
Please try the Alpha 1.39.1 which includes Neo2 layouts: https://github.com/klausw/hackerskeyboard/wiki/TestReleaseOptIn

**Comment by klausw** [comment]
Closing, 1.39.1 is now set as live on Play Store. It may take a day or so until your device sees the update.
