### ISSUE TITLE
Play Store update

### ISSUE THREAD

**Issue by Arwany** [klausw/hackerskeyboard#497]
Hi,

this might be silly question, but I would really like to know if you guys are planning to update the play store app.

I am using Hacker's Keyboard since I ever knew Android, and I love everything about it, but your last update was on december 2013, which is why I am writing this.

Do I need to build the APK myself everytime you have release (or some new implementations), or do you have any planning for the future?

Thank you for your time and efforts.

**Comment by Djhg2000** [comment]
There is a 2015-04-22 release on the official F-Droid repo. It is signed using a different key though so Android requires you to uninstall the Play Store version before you can upgrade.

**Comment by Arwany** [comment]
Thank you. I installed it from F-Droid.
