### ISSUE TITLE
clarify license

### ISSUE THREAD

**Issue by ZeroChaos-** [klausw/hackerskeyboard#501]
I cannot find a license anywhere, can you please tell us the terms under which we can use/modify/redistribute/etc?

**Comment by matthewmorris085** [comment]
I would like license please

**Comment by tohateam** [comment]
It seems that the author ignores such questions. I even wrote on his e-mail, but the answer never received.

**Comment by TPS** [comment]
Reading through https://github.com/klausw/hackerskeyboard/issues/13#issuecomment-174059382, it looks to be [Apache 2.0](http://choosealicense.com/licenses/apache-2.0/).

**Comment by TPS** [comment]
@klausw [has answered authoritatively that this project  is](https://github.com/klausw/hackerskeyboard/issues/512#issuecomment-255282531) [Apache 2.0](http://choosealicense.com/licenses/apache-2.0/)!

**Comment by TPS** [comment]
@ZeroChaos- @klausw Either of you can close this issue now, though, @klausw, in the project settings, if you set the license correctly, it'd be eminently clear in the GitHub GUI itself.

**Comment by klausw** [comment]
Sorry about the confusion, the license file appears to have gone missing when I imported the project from Google Code. It's Apache 2 licensed.

**Comment by ZeroChaos-** [comment]
@klausw thanks!

**Comment by Gothicania** [comment]
> @klausw [has answered authoritatively that this project is](https://github.com/klausw/hackerskeyboard/issues/512#issuecomment-255282531) [Apache 2.0](http://choosealicense.com/licenses/apache-2.0/)!
