### ISSUE TITLE
Need a method to forcibly show the keyboard any time

### ISSUE THREAD

**Issue by mikeloeven** [klausw/hackerskeyboard#512]
So sometimes there are times when you need a keyboard but dont have one because android doesent see a text context. An example of this is playing browser based games that need wsad input and lack touch support

**Comment by demaborisov0** [comment]
Open

**Comment by glchisenhall** [comment]
I agree with most of the OP's statement. However for me, I would just like to be able to use the function keys. As of right now, they have little to no use for me. Although, I'm not sure the uses I'd have are even supported on android anyhow, but just knowing one way or the other would be helpful. Unfortunately, as OP stated, currently no method exists to display the keyboard, thus, is my predicament.

**Comment by TPS** [comment]
The `☑️ Use permanent notification` setting is designed specifically for this scenario.  Choosing the notification opens the keyboard anytime.

**Comment by mikeloeven** [comment]
May need to look at your notification API or the Manifest permissions of the app the persistent notification does not show up on my device even though the option is selected

Using a Galaxy S5 with AT&T
running marshmallow

**Comment by TPS** [comment]
Since I run Android 4.4.x, it works fine.  Obviously, HK hasn't been updated/released since then.  What do _you_ think, @klausw?

**Comment by mikeloeven** [comment]
You might want to go the accessibility route with this function and use the overlay API to show a floating action button that can be dragged around the screen like the call shortcuts

**Comment by yassine987** [comment]
In [LatinIME](https://github.com/klausw/hackerskeyboard/blob/master/java/src/org/pocketworkstation/pckeyboard/LatinIME.java#L507) Class (_Line 507_) the developer use 
`notification.setLatestEventInfo(getApplicationContext(), title, body, contentIntent);`
This method was removed in M (api 23)
I suggest to delete the line and add this before **Line 506**
```
Notification notification = new Notification.Builder(getApplicationContext())
                    .setAutoCancel(false) //Make this notification automatically dismissed when the user touches it -> false.
                    .setTicker(text)
                    .setContentTitle(title)
                    .setContentText(body)
                    .setWhen(when)
                    .setSmallIcon(icon)
                    .setContentIntent(contentIntent)
                    .getNotification();
```

for more information about the issue [StackOverflow](http://stackoverflow.com/questions/32345768/cannot-resolve-method-setlatesteventinfo)

**Comment by TPS** [comment]
@yassine987 2 suggestions:
- [The vast majority of users (as of this note) use Android < M](https://developer.android.com/about/dashboards/), so support for all versions _could_ be done via conditional statement(s).
- Once the above is worked out, it'd be amazing if this could be turned into [a proper PR](https://github.com/klausw/hackerskeyboard/compare).

Thanks for the work on this! :clap:

**Comment by mikeloeven** [comment]
I would still be using lollipop if it wasn't for AT&T's forced ninja updates

**Comment by yassine987** [comment]
@TPS 
I tested the app with the above changes in 3 devices **Samsung GT-S7580 (Android 4.2.2, API 17), Samsung SM-G355H (Android 4.4.2 API 19), Samsung SM-J200F (Android 5.1.1, API 22)**, the Use permanent notification works great, unfortunately, don't have an M device for making sure it solved.

**Comment by mikeloeven** [comment]
If you can post a link to the updated APK I'll test it for you

**Comment by yassine987** [comment]
@mikeloeven [APK](https://drive.google.com/open?id=0B-LH3dcJu6ixa1p1TmVFUmZNdEU)
waiting for the result ^_^

**Comment by mikeloeven** [comment]
Permanent notification is confirmed working on marshmallow

**Comment by yassine987** [comment]
I think @klausw is the only one who can update Hacker's keyboard in Play Store.

Now, I'm working on a keyboard app based on hacker's keyboard with a new feature, will be available in December 2016 (If everything goes as planned), I can let you know when it's available in Play Store.

**Comment by TPS** [comment]
I'd love to try it.…  Is your dev fork on GitHub?  & would you mind pulling in all the other [work](https://github.com/klausw/hackerskeyboard/network) & [PRs](https://github.com/klausw/hackerskeyboard/pulls) from other folks here, & acknowledge all of the above via a clear [Apache-2.0–compatible license](https://github.com/klausw/hackerskeyboard/issues/501)?

**Comment by yassine987** [comment]
@TPS not yet, but I create a new one for this issue.

I have some questions if you don't mind
- As I mentioned above, I'm working on a keyboard app based on hacker's keyboard with a new feature, different themes etc...., and I'm planning to publish it on Github and Play Store. So, is it ok if I push it as a new Repository?
- Is it legal to publish it at Play Store (I'll mention Hacker's keyboard in my about) ?

**Comment by TPS** [comment]
@yassine987 IANAL nor the original author (<kbd>@klausw ___is!___</kbd>), but, AFAICT:
- I think it'd better to _fork_ from here, as it's more likely to receive more attention & help doing so, given that your app's a derivative  of this 1 _only_, with your additions & modifications.
- [As mentioned above, as many of us assume an Apache 2.0 license (@klausw, a clarification would be ___amazing!___)](https://github.com/klausw/hackerskeyboard/issues/512#issuecomment-254197428), you should be ok if you follow [its terms](http://choosealicense.com/licenses/apache-2.0/) correctly.

**Comment by mikeloeven** [comment]
@yassine987 found a slight issue with your build its launching as a delayed startup instead of at boot causing the system to default to the system keyboard each restart

**Comment by TPS** [comment]
@yassine987 I forgot to mention _maybe_ the **most** important reason to fork this repo:  Inheriting the issues here, as you solve them & mention that you did so, you immediately increase your userbase among the users tracking these issues.

**Comment by klausw** [comment]
@yassine987 @TPS Sorry about the long silence, things have been too busy. Thank you for investigating this issue, I'll merge this and look into getting a new release out (any year now). I can apply the change manually, but if you want attribution in the source it would be easiest if you can make a pull request.

As far as forking and publishing on the Play Store is concerned, you're welcome to do so. The Apache 2.0 license allows this, but please change the application name and contact info in documentation to make it clear that it is a modified version. That's mainly to avoid user confusion and ensure that contact attempts go to the right author.

The Play Store releases are signed with a cryptographic key, so you'd need a different package name and use your own signing key. That way the new application can be installed alongside the current package, it can't replace it. Before you ask, I don't intend to share the existing key. I think it wouldn't be fair to existing users to have software updated in-place with someone else's version, especially considering that a keyboard is security sensitive. But I'd be willing to provide links to alternate maintained versions if mine continues being neglected.

**Comment by klausw** [comment]
I've included this change in the latest alpha version 1.39.0.

You can use this link to opt-in as a tester for the alpha version: https://play.google.com/apps/testing/org.pocketworkstation.pckeyboard

It may take a few hours for the new version to propagate, you can check your version at the bottom of the keyboard's settings menu.

**Comment by klausw** [comment]
Closing, 1.39.1 is now set as live on Play Store. It may take a day or so until your device sees the update.

**Comment by typxxi** [comment]
1.39.1 arrived - a few hours ago and I noticed that after I tfied to use Ctrl + a which did not work anymore - instead a hint appeared and therefore I checked the configuration and finally found that new option.

@Klaus: Thanks for the update - hope to see more

**Comment by RSW2019** [comment]
I have a little app that does this, you can use it to bring up any keyboard you have installed, gboard or whatever

https://play.google.com/store/apps/details?id=com.rswspinningyarns.keyboardlaunchernoads
