### ISSUE TITLE
Esperanto letters

### ISSUE THREAD

**Issue by leonerd** [klausw/hackerskeyboard#524]
Would it be possible to add the Esperanto alphabet letters to one of the layouts? Ideally just the internationalised/English one. The required letters are

'ĉ' [U+0109] - LATIN SMALL LETTER C WITH CIRCUMFLEX
'Ĉ' [U+0108] - LATIN CAPITAL LETTER C WITH CIRCUMFLEX

'ĝ' [U+011d] - LATIN SMALL LETTER G WITH CIRCUMFLEX
'Ĝ' [U+011c] - LATIN CAPITAL LETTER G WITH CIRCUMFLEX

'ĥ' [U+0125] - LATIN SMALL LETTER H WITH CIRCUMFLEX
'Ĥ' [U+0124] - LATIN CAPITAL LETTER H WITH CIRCUMFLEX

'ĵ' [U+0135] - LATIN SMALL LETTER J WITH CIRCUMFLEX
'Ĵ' [U+0134] - LATIN CAPITAL LETTER J WITH CIRCUMFLEX

'ŝ' [U+015d] - LATIN SMALL LETTER S WITH CIRCUMFLEX
'Ŝ' [U+015c] - LATIN CAPITAL LETTER S WITH CIRCUMFLEX

'ŭ' [U+016d] - LATIN SMALL LETTER U WITH BREVE
'Ŭ' [U+016c] - LATIN CAPITAL LETTER U WITH BREVE

Likely these could be added on the pop-out menus as you hold the unmodified versions of the letter keys, as with many of the other accented versions.

**Comment by redyoshi49q** [comment]
I'd greatly appreciate the merging of #525 into this project's master branch.  I have sorely felt the absence of Esperanto special characters, and I would appreciate not having to install the .APK of a fork for this feature.
