### ISSUE TITLE
Ctrl-A doesn't work anymore

### ISSUE THREAD

**Issue by CSDragon** [klausw/hackerskeyboard#533]
Somehow it got disabled and shows a pop up saying it's disabled but there doesn't seem to be a way to re-enable it. There are no setttings in the Hacker's Keyboard app

**Comment by CSDragon** [comment]
Hmm, apparently the settings is hidden away on the vertical keypad only. It is neither in the app nor on the horizontal keypad. Considering the kind of person who would use this app is the kind of person who would hold their phone horizontally at all times you should probably fix that. But still how did Ctrl-A get disabled? I didn't do that.

**Comment by tinydynamite00** [comment]
The default <code>^a</code> key binding was switched to <code>^<ALT>a</code> to avoid conflict as that key binding is interpreted by some apps (and Windows) as «select all». You can revert to the old key binding in Android Settings > Language & Keyboards > Virtual keyboard (Android 7.0+).

**Comment by CSDragon** [comment]
Of course it's select all, what else would it be? That's what it was before.

**Comment by tinydynamite00** [comment]
The way to fix it still stands ;)

**Comment by CSDragon** [comment]
Still, it makes no sense to disable a basic functionality of a keyboard

**Comment by CSDragon** [comment]
Also: changing the settings for the default Virtual Keyboard (Android 7.0+) wouldn't change the Hacker's Keyboard. I was able to find the Hacker's Keyboard settings in Language & Keyboards though. Also, I have Samsung, so I don't even get the Virtual Keyboard (Android 7.0+), my phone came with the Samsung keyboard.

**Comment by TPS** [comment]
@CSDragon You ___really___ need to read #487 & issues referred therein to realize why _this_ issue will end up <kbd>Won't Fix/Revert</kbd>.

**Comment by CSDragon** [comment]
So what people accidentally hit Ctrl-A because they have fat fingers? Give THEM the option to disable it. Don't auto-disable it for the rest of us. And then hide the option to change it back in the Android System menus instead of the Hacker's Keyboard options.

Ctrl-A is one of the most important basic keyboard shortcuts. How can the Hacker's Keyboard be a true PC keyboard if it doesn't act like a PC keyboard 100% of the time by default.

**Comment by KingRider** [comment]
I think only root is work (ctrl+alt+a) :( .. i try not work and no root! my android 7.1

**Comment by klausw** [comment]
There's an option to change it back to the original behavior, but I'm going to keep the default to require Ctrl-Alt-A. Yes, some people may not like it, but I do think that the risk of inadvertent data loss due to an accidental "select all" was significant enough to make it worth changing. It's easier to hit Ctrl-A by accident on the soft keyboard than it would be on a physical layout.
