### ISSUE TITLE
Umlauts are very small on FP2

### ISSUE THREAD

**Issue by Tuffiglig** [klausw/hackerskeyboard#535]
Hallo.
The Umlauts are very small and hard to tip on my Fairphone 2 with the OS Fairphone Open 16.11.0 Android 5.1
Shown here in the Screenshot:
![tmp_12830-screenshot_2016-12-27-13-50-21-1778267992](https://cloud.githubusercontent.com/assets/15114290/21500278/a481e35e-cc3d-11e6-8957-b08d5aae95eb.png)

I didn't found a setting to change the size. Is there any?

Best regars,
Tuffi

**Comment by tohateam** [comment]
Press the Shift key and long press to enter the alternate characters.

**Comment by Tuffiglig** [comment]
Sorry. I was to unclear :-(
How I get the Upper letters, I know.
My Problem is: With the new phone, the alternate characters are very, very small. It is very hard to press them, because they are too small.
With the old phone, they where as large as the normal characters.
I hope i was a little bit more clear this time.

**Comment by mase76** [comment]
I have the same problem on my FP2. I used the same version of HK on my last device with Cyanogenmod without problems.

**Comment by Herzfinsternis** [comment]
Same problem with Lineage OS 14.1 on ZUK Z1 (ham). I used the same version of Hackers Keyboard with Cyanogenmod 13 without that issue.
Even though this seems to be affected by the OS (unfortunately fiddling with display settings didn't help), I think that it would be reasonable to make the popup keys the same size as the keyboard keys. It is not only the characters, that are too small, but the keys themselves.

I was not able to take a screenshot when such a key has the focus, so you could see the size of the keys. :-(

![hackers_keyboard_popup_keys_too_small](https://cloud.githubusercontent.com/assets/25349375/24071265/416d59b2-0bce-11e7-98ae-ebb972323e1b.png)

**Comment by TPS** [comment]
Have y'all tried fiddling w/ `Settings » Theme and Label Settings > Suggestion Label Scaling`?

**Comment by Herzfinsternis** [comment]
I did so. But it is not the suggestions we are talking about. This is about the popup-keyboard, that shows when you long-press a key (key with letter a for example: 🅰). The popup-keyboard is not affected by that setting. The "Key label scaling" does affect that keyboard too, but that is no satisfiable solution to me.

**Comment by TPS** [comment]
That's right, @Herzfinsternis, I was mistaken.  I fixed it above.

That's odd!  I just realized that in your screenshot, your pop-up keyboard font-size is ___much___ smaller than the key font-size.  Maybe it has to w/ y'all using Android alternatives?  HK _is_ built on very old [Gingerbread (Android 2.3.×) code](https://github.com/klausw/hackerskeyboard/issues/487#issuecomment-255554653) & maybe they don't support that version correctly?  Or did an older version of HK work correctly for y'all?

**Comment by Herzfinsternis** [comment]
To me it seems as if Android 7.1 caused the problem, as I did not have problems with Android 6.0 and Hackers Keyboard and I know Google did change a few things related to display settings. On the other hand Tuffiglig uses Android 5.1.
I will try to test Hackers Keyboard with Android Studio emulator. I am new to android development. So this might take a while...

**Comment by Tuffiglig** [comment]
On my company phone Motorola Mot G4 Plus with Android 7.0, HK is working correctly.
TPS mentioned, that HK is build on a very old codebase. Is it possible to build it on a newer one and test it?

**Comment by Herzfinsternis** [comment]
A few odd observations:
- www.kicker.de displays a mobile page in emulator but a desktop page on my phone
- https://play.google.com/store/apps/details?id=com.rafalzajfert.displaymetrics compatible with android 4.1+ on my phone tells me my display is 480 dpi just like my build.prop says
-  https://play.google.com/store/apps/details?id=com.noser.android.apps.tools compatible with android 1.6+ on my phone tells me my display is 160 dpi

Is it possible to enable the debug log for HK? Where would I find it on my phone?

**Comment by TPS** [comment]
@Tuffiglig: Rebuilding on a [newer version of what's now GBoard](https://android.googlesource.com/platform/packages/inputmethods/LatinIME/+/master/java/src/com/android/inputmethod/keyboard) would be almost-complete rewrite, & worthy of a ___major___ version increment. (Good luck! 🍀) As  @KlausW [explains (in same link above)](https://github.com/klausw/hackerskeyboard/issues/487#issuecomment-255554653) re: a _lot_ of new feature requests (& some bugs):
>… is not supported and is not going to be - the underlying Gingerbread AOSP keyboard that the code is based on doesn't support it, and it's not really feasible to backport this. I think it would be easier to start fresh with a more current upstream AOSP keyboard and port the layouts and other features over, but I don't have any plans to do so.

@Herzfinsternis I've no idea whether debug logs are even possible via UI.  Maybe @KlausW, @DSalt, @SBeyer, @Poussinou, or really [active dev](https://github.com/klausw/hackerskeyboard/network) could help out?

**Comment by Herzfinsternis** [comment]
I managed to debug HK on my device and in emulator.

`    public Keyboard(Context context, int defaultHeight, int xmlLayoutResId, int modeId, float kbHeightPercent) {
        DisplayMetrics dm = context.getResources().getDisplayMetrics();`

Device:
DisplayMetrics{density=3.0, width=1080, height=1920, scaledDensity=3.0, xdpi=160.421, ydpi=159.895}

Emulator:
DisplayMetrics{density=2.5, width=1080, height=1800, scaledDensity=2.5, xdpi=400.0, ydpi=400.0}

This seems to be a problem with (and originating from) LineageOS build for ZUK Z1 (ham). Any ideas what files/values need to be edited to correct the display metrics?
https://github.com/LineageOS/android_device_zuk_ham
As mentioned before, I am not an android developer. So any hint would be great. Otherwise I would have to explain everything again over at LineageOS.

**Comment by TPS** [comment]
@Herzfinsternis Most devs are _very_ amenable to reading a linked issue, so unlikely you'd have to explain much. Try them & see.

**Comment by Herzfinsternis** [comment]
No update from LineageOS developers yet. But I found out that both devices (Fairphone2, ZUK Z1) are run on Snapdragon 801 (MSM8974). Maybe that's the source of the problem.

**Comment by TPS** [comment]
@Herzfinsternis My best hunch is it _probably_ has nothing really to do w/ hardware nor OS version _per sé_, but everything to w/ LineageOS v7's support for apps written for Android v2, as, I'm sure, almost any stock Android (or close _enough_ equivalent) from 2.3.× through 7.1.1 (on much of which I've run HK) on _almost_ all hardware does handle it just fine. Do keep us updated w/ whatever the L-OS devs say.

**Comment by klausw** [comment]
@Herzfinsternis wrote:
> Device:
> DisplayMetrics{density=3.0, width=1080, height=1920, scaledDensity=3.0, xdpi=160.421, ydpi=159.895}
> 
> Emulator:
> DisplayMetrics{density=2.5, width=1080, height=1800, scaledDensity=2.5, xdpi=400.0, ydpi=400.0}

I think that's the problem right there - the device reports a 1920x1080 resolution with 160 dpi, so that means it claims a screen size of 12 inches by 6.7 inches. The GUI will draw characters so that they are scaled appropriately for that screen size, but if the actual device is phone-sized they'll end up way too small.

**Comment by klausw** [comment]
@TPS Yes, the difference is that key labels use a [rather complicated method](https://github.com/klausw/hackerskeyboard/blob/master/java/src/org/pocketworkstation/pckeyboard/LatinKeyboardBaseView.java#L942) to pick a label size. For the pop-up, I'm expecting the operating system to do the right thing. Honestly I'm not too motivated to fix this, if the vendor decides to report their phone as having a laptop-sized screen they should fix that, it'll also break other content.

**Comment by Herzfinsternis** [comment]
I too think that should be fixed by the "vendor". Fairphone Open and Lineage OS are both open source. I believe it should be possible to fix that somehow. Unfortunately there is [no progress](https://jira.lineageos.org/browse/BUGBASH-291) so far. Perhaps I will find someone on [XDA](https://www.xda-developers.com/) who can help me or push me in the right direction.

**Comment by TPS** [comment]
@Tuffiglig I found similar bug report as @Herzfinsternis's, but w/ FairPhone, so this is a known issue FIXED in latest OS version, not a problem w/ HK.

https://forum.fairphone.com/t/google-cardboard-screen-scale-issue-might-be-fp2-reports-wrong-dpi/11706/38

Mark Closed/Invalid FTW?

**Comment by klausw** [comment]
@TPS thanks for digging that up. Cardboard actually has a database of misconfigured devices since this was a rather common problem, but most mismatches weren't this bad.

**Comment by Tuffiglig** [comment]
For the Fairphone the Problem was fixed in Version Fairphone Open OS 17.02
I switched to AnyKeyboard in the meantime, because this bug was very annoying, and didn't realised that it was fixed.
On my device it works correct now. Time to deinstall AnyKeyboard :)
![photo5415903200357230524](https://cloud.githubusercontent.com/assets/15114290/24719196/2021c184-1a39-11e7-94d1-08c64eb2fc36.jpg)

**Comment by Herzfinsternis** [comment]
Problem [solved](https://code.fairphone.com/gerrit/gitweb?p=fp2-dev/device/fairphone_devices/fairphone.git;a=commitdiff;h=ed0063db92632fa34929d5cdafd5df1f0dcf9c40;hp=e179c55b62296c6478d25e3ffe5d9fab292e9f96)! 

After updating /system/build.prop (adding the line `qemu.sf.lcd_density=480` after `ro.sf.lcd_density=480`) everything works as expected.

I am so very happy! Thanks to all of you!
