### ISSUE TITLE
Missing ? on 5-row compact layout

### ISSUE THREAD

**Issue by Yup746** [klausw/hackerskeyboard#562]
I can't for the life of me find the questionmark. If it might be useful, I'm using marshmallow on an sm-G920F (Galaxy S6). Default settings, except for having changed portrait mode to 5-row compact layout. I like it in portrait for using it in vi for example (swiftly being able to use esc). I can't imagine it being meant to be MIA, so I thought I'd send a bugreport.

**Comment by Yup746** [comment]
Edit: The / is ofcourse also nowhere to be found

**Comment by TPS** [comment]
Well, <kbd>/</kbd> is in the lower right-hand corner, right above <kbd>→</kbd>. <kbd>?</kbd> is <kbd>Shift</kbd><kbd>/</kbd>.

Tip: Turn on `Settings > Theme and Label Settings » Labeled Alternate Keys: Show all hint labels` to see alternate keys more easily.

**Comment by Yup746** [comment]
![tmp_16381-screenshot_20170322-0732461961515815](https://cloud.githubusercontent.com/assets/26579956/24185134/de5b9846-0ed1-11e7-8c9b-db7212fa5b20.jpg)
I see now, it was hidden under the speach to text button, thanks!
