### ISSUE TITLE
Verticle bar on the top-left most key, in portrait mode.

### ISSUE THREAD

**Issue by patelpreet422** [klausw/hackerskeyboard#568]
![img_20170416_001450](https://cloud.githubusercontent.com/assets/25868975/25066146/98a7baa6-220d-11e7-80e6-1177749a45d7.jpg)This verticle bar on the top-left most key is always visible in portrait mode, once I switch to landscape mode it magically disappears. Can we fix it!

**Comment by TPS** [comment]
What device/OS version are you running?  I don't have that on ___any___ of mine!

**Comment by patelpreet422** [comment]
DEVICE :- Xiaomi Redmi Note Prime[ROOTED]
OS :- Android 4.4.4
MIUI :- 8.1(Global ROM-Stable)

**Comment by TPS** [comment]
2 of my devices run Android 4.4.×, so I think you'll have to look for a device-specific fix on this 1, possibly due to MIUI not being stock Android or lack of Google integration.  Any other apps exhibit weird UI glitches?

**Comment by patelpreet422** [comment]
@TPS  Well, Not really. This is first time I've something like this. Other apps just works fine.   
Seems like this one is quite special !

**Comment by TPS** [comment]
Ok, then, but [MIUI's own pages for the app show no such problems](https://www.google.com/search?q=%22hacker%27s+keyboard%22+site%3Amiui.com), so maybe other changes you've made to your setup are affecting HK?

**Comment by patelpreet422** [comment]
Well I personally changed just one settings in HK, to be honest.
> - Keyboard view settings.
 ->(Changed) Keyboard mode, portrait [FROM 4-row layout, TO full 5-row layout]

**Comment by TPS** [comment]
No, I don't mean _in_ HK, but to _your device_: e.g., something due to rooting or other configuration.  According to all those links on MIUI.com, HK works just fine on that software/device standard combo.

**Comment by patelpreet422** [comment]
Till I remember I haven't made any major changes , may be something that I might have done  accidentally or it just went out of mind, what so ever may be the reason. I suspect there are no more changes to the device.
