### ISSUE TITLE
No / on the 5-row compact layout (US qwerty)

### ISSUE THREAD

**Issue by EnoraNedelec** [klausw/hackerskeyboard#590]
Hi!
Thanks for the hackerskeyboard! It's a great tool! I just have one request: I can't find the Slash (/) on the 5-row compact layout (US qwerty) keyboard (even in the Fn "sub-keyboard"). 
I would be great to add!

**Comment by EnoraNedelec** [comment]
Sorry, I haven't seen the others question. For those who are wondering where the / is, it's on the long press on the micro.

**Comment by jimbo1qaz** [comment]
What key is a micro?

**Comment by MagTun** [comment]
Yes, I meant microphone! Sorry for the confusion!
