### ISSUE TITLE
Add new theme

### ISSUE THREAD

**Issue by keeganjk** [klausw/hackerskeyboard#610]
This has few options for theming, the latest being Ice Cream Sandwich (4.0), an Android version that is almost 7 years old. The latest Android version is 8.0.

This needs an interface update.

**Comment by PorygonZRocks** [comment]
I have a pull request for this open [here](https://github.com/klausw/hackerskeyboard/pull/602).

**Comment by BeeeWall** [comment]
This can probably be closed now, as the Material themes have been available for a little while now.
