### ISSUE TITLE
English dictionary missing from Play Store

### ISSUE THREAD

**Issue by resuna** [klausw/hackerskeyboard#624]
Is there an alternate source for the dictionaries?

**Comment by LissieTilbrook** [comment]
Wondering the same thing!

**Comment by LissieTilbrook** [comment]
Since I can't edit my previous comment, I'm glad I have a backup APK from my previous phone of the dictionary.

**Comment by johnyfivewow** [comment]
Love the app, but need the English completion dictionary. It's the only language I know and I'm too tired to learn and then teach everyone I will ever text another language.

If anyone strumbles across this thread about an issue they don't have and\or just has some Carebear left in them and could post an English Completion Dictionary APK somewhere I bet more than one English speaker would really appreciate it.
Thank you,
~johny

**Comment by johnyfivewow** [comment]
Oh. I feel dumb. Download AnySoftKeyboard from Google Play. Hacker's learns English from ASK's completion dictionary.

**Comment by LissieTilbrook** [comment]
I am hosting the English dictionary here: https://github.com/LissieTilbrook/HackersKBEnglishDic/blob/master/HK%20_English%20(en)_%20Dictionary_1.3.apk if anyone needs it.

**Comment by tioteath** [comment]
Pretty much useless withou engl8sh dictionary. But why it has been removed?

**Comment by resuna** [comment]
Any comment from @klausw ?

**Comment by affectiosus** [comment]
@LissieTilbrook you're a life saver. Thank you for uploading the dictionary.

**Comment by tryforsure** [comment]
@LissieTilbrook thanks for sharing.

**Comment by tryforsure** [comment]
@LissieTilbrook thanks for sharing.

**Comment by LissieTilbrook** [comment]
@affectiosus and @tryforsure, you're welcome!

**Comment by nakedpwr** [comment]
This actually is a situation that illustrates brains over Brawn. Resourcefulness is something that I thought was just a word until I joined the military and after two Wars and a marriage or two and birth of three beautiful children, it's nice to see that there is actually a real community with camaraderie and an idea of what resourcefulness actually means. Thank you for reposting that. It means a lot to somebody that's a little older and kind of used to the keyboard used for a long time.

**Comment by Junis07** [comment]
I found dictionaries here: https://apkpure.com/developer/Klaus%20Weidner

Tried the EN, DE, RU and CZ - works without problems.

**Comment by TPS** [comment]
#655 has update.

**Comment by klausw** [comment]
The English dictionary is back on the Play Store, sorry about the confusion. It got taken down due to incomplete content rating metadata.
