### ISSUE TITLE
Must be converted to Gradle

### ISSUE THREAD

**Issue by mirabilos** [klausw/hackerskeyboard#628]
https://github.com/klausw/hackerskeyboard/wiki/BuildingFromSource says to use Android Studio, which is IntelliJ, but my (pre-existing… I don’t have the room to install this moloch twice) (Un)IntelliJ installation’s help says:

> Starting with the IntelliJ IDEA version 2016.1, non-Gradle Android projects are not supported.

This is… kinda… bad.

**Comment by syk-yaman** [comment]
It was done on #635

**Comment by klausw** [comment]
The main branch is now using gradle.
