### ISSUE TITLE
[Request] Support for Sticky Keys

### ISSUE THREAD

**Issue by VHrishikesh** [klausw/hackerskeyboard#638]
I wasn't able to find this feature. I just want an ability to use Sticky keys like Shift, Ctrl, etc. By sticky keys, I mean,that I just want to use shortcuts like Ctrl+A, etc.

**Comment by TPS** [comment]
They should just work.  Or do you mean to use <kbd>Ctrl</kbd> ***,*** <kbd>A</kbd> (meaning each key separately) as = to <kbd>Ctr</kbd> ***+*** <kbd>A</kbd>?  That option, AFAICT, doesn't currently exist.

**Comment by VHrishikesh** [comment]
Yeah. I noticed that what I had asked for already works. Sorry for this post.
