### ISSUE TITLE
Korean Input

### ISSUE THREAD

**Issue by Aldebrand13** [klausw/hackerskeyboard#642]
First off, let me say that I love your app. It's been super useful to me over the past few years. I am starting to learn Korean, and while Google does have a Dvorak layout now, it's super clunky, and doesn't have the ability to use arrows or Ctrl functions. Is there any plan for support for this layout? Or is it going to be too complex?

**Comment by klausw** [comment]
Sorry, I don't have any plans for this - see the FAQ: https://github.com/klausw/hackerskeyboard/wiki/FrequentlyAskedQuestions#can-you-add-support-for-chinesejapanesekoreanother-specific-language-layouts

> *Can you add support for Chinese/Japanese/Korean/(other specific language) layouts?*
> The current code is strongly oriented to alphabetic languages and is based on a fairly simple mapping from keypresses to output characters. Ideographic languages with complex input methods would need very different approaches, and I do not plan to support Chinese/Japanese/Korean and similar languages due to their complexity and lack of language knowledge on my part. Note that you can easily keep multiple keyboards installed and manually switch between them, for example using Hacker's Keyboard just for SSH while using the system keyboard for other applications.
