### ISSUE TITLE
English dictionary no longer exists

### ISSUE THREAD

**Issue by forrestv** [klausw/hackerskeyboard#651]
The "Dictionary available" annotation on English isn't shown in the "Input Languages" dialog after a fresh install, and there is no English dictionary available at https://play.google.com/store/apps/developer?id=Klaus+Weidner.

**Comment by TPS** [comment]
#655 has update.

**Comment by klausw** [comment]
The English dictionary is back on the Play Store, sorry about the confusion. It got taken down due to incomplete content rating metadata.
