### ISSUE TITLE
Keylogger function

### ISSUE THREAD

**Issue by protoloo** [klausw/hackerskeyboard#654]
Hello. I do not know if there is already something similar, but I would like to ask to add to this app the functionality of a keylogger program; more maybe other features like password to access the logs, etc.

In addition to the immediate functionality, I think it can be useful in those cases where we lend the phone, insert passwords and forget them, or simply to have a sort of "chronology" of our thoughts :D

**Comment by TPS** [comment]
Umm, please, no.  Also, I'm reasonably sure that'd violate something in Google's TOS.

**Comment by protoloo** [comment]
... I read your comment now, and if I respect your opinion, I'll point out that:

1) There is not only Google. A free app should be principally on F-Droid.
2) Being open-source, anyone can see, edit and verify the code. making life very difficult for bad guys.
3) If something is useful, safe and (as in this case) controllable, why should not I request it?
4) The function that I requested, works offline and the app itself does not have internet access, so ..

**Comment by TPS** [comment]
It'd probably violate F-Droid inclusion requirements moreso!

Besides, the way Android is setup now, the Internet permission is almost meaningless, as keylogger data would have to stay encrypted __&__ on non-synced internal app storage on a non-root device to have ½ a chance to keep from getting out.

Honestly, if you _really_ want this, fork it, change the name & assets to something __clearly__ explaining what you're doing, & sit back to watch the🔥🌋💩 fly/hit. 🙇

**Comment by klausw** [comment]
I'm not sure if you're serious or not, but I'm definitely not going to add a key logger feature to the application. There's way too much potential for misuse for this, on top of security risks and violating both user trust and app store guidelines.
