### ISSUE TITLE
App (temporarily) missing from Play Store

### ISSUE THREAD

**Issue by klausw** [klausw/hackerskeyboard#655]
FYI, Hacker's Keyboard was removed from Play Store today, this was due to me not having filled out an age rating questionnaire. I did so now, it should be back in a few hours once that's been processed by the system.

The dictionaries are still offline, I need to fill out more forms for those and rustle up a now-mandatory promo image. Also, in case you're wondering, those are likely to have a restrictive age rating since the dictionaries may contain naughty words, and I'd rather err on the side of caution since I can't confirm this myself for languages I don't speak.

**Comment by TPS** [comment]
Thanks very much for the info & update! :bow:

**Comment by TPS** [comment]
@klausw While republishing, is it possible to expose the dictionary apk _sources_, each into its own repo, for the sake of, e.g., [publishing via F-Droid](https://github.com/klausw/hackerskeyboard/issues/508), to help avoid this in future? :bow: :pray:

**Comment by klausw** [comment]
Hacker's Keyboard is showing on Play Store again, and so are most of the dictionaries. The English one is still not showing, I'll update #624 / #651 once it's back.

**Comment by klausw** [comment]
@TPS , I'll look into uploading dictionary APKs and/or sources separately.

**Comment by TPS** [comment]
@klausw Thanks _very_ much! 🙇
