### ISSUE TITLE
Not found key ctrl, tab, alt, right button, left button, top button, down button on android 8.0 in samsung j4

### ISSUE THREAD

**Issue by Maulaya** [klausw/hackerskeyboard#666]
when used on my smartphone, the keys ctrl, alt, tab, top button, down button, left button, and right button, no, the position of Android 8.0 samsung j4, please immediately fix this, I really need it

**Comment by TPS** [comment]
Screenshot?

**Comment by Maulaya** [comment]
Pada tanggal Min, 23 Sep 2018 20:15, TPS <notifications@github.com> menulis:

**Comment by Maulaya** [comment]
![screenshot_20180923-201629_termux 1](https://user-images.githubusercontent.com/25793649/45928537-995bb780-bf6f-11e8-8e3e-8cd6c067e359.jpg)
![screenshot_20180923-201642_whatsapp 1](https://user-images.githubusercontent.com/25793649/45928550-b2fcff00-bf6f-11e8-8d0b-da4a4df262b4.jpg)
![screenshot_20180923-201658_chrome 1](https://user-images.githubusercontent.com/25793649/45928562-d1fb9100-bf6f-11e8-800d-6fa9f10ff049.jpg)

**Comment by TPS** [comment]
Then close FTW! :bow:
