### ISSUE TITLE
Keys are hard to read due to low contrast color scheme

### ISSUE THREAD

**Issue by jottr** [klausw/hackerskeyboard#671]
All the black keys are almost impossible identify, due to the low contrast of the color scheme.   
Maybe the color scheme could be updated to match the official Android keyboard (Gboard)? 

Especially with low screen brightness or on small screens, this causes significant usability issues.

![keyboard](https://user-images.githubusercontent.com/2744198/47435376-c71d6180-d7a4-11e8-97de-e1ea61a52f4b.jpg)

**Comment by jottr** [comment]
I tried all available drawing methos. I didn't see any changes. 
Also, the color looks the same on all off my Android devices (various android versions).

**Comment by klausw** [comment]
This should be improved as of v1.40.1 / commit ca39f3a7d5bec077c8ebd5cc95503f5b99129a3c .
