### ISSUE TITLE
Glide typing / Swype support

### ISSUE THREAD

**Issue by Maccer1** [klausw/hackerskeyboard#672]
Hey, nice keyboard!
I just wanted to point out that there's a feature called Glide typing (on gboard) and Swype (on other keyboards) that let's the user type sliding the finger across the keyboard instead of pressing each key.
I think it would be great if your keyboard had it as well :)

Here are some links on [how AnySoftKeyboard implemented it](https://github.com/AnySoftKeyboard/AnySoftKeyboard/issues/264), [how Swype works](http://www.krishnabharadwaj.info/how-swype-works/) and a [implementation of Swype written on C++](https://gist.github.com/krisys/71acdef7a33ed40bd586)

**Comment by daraul** [comment]
Why did you close this, @Maccer1? I'd love to see glide / swipe on this board

**Comment by Terrorysta** [comment]
> Hey, nice keyboard!
> I just wanted to point out that there's a feature called Glide typing (on gboard) and Swype (on other keyboards) that let's the user type sliding the finger across the keyboard instead of pressing each key.
> I think it would be great if your keyboard had it as well :)
> 
> Here are some links on [how AnySoftKeyboard implemented it](https://github.com/AnySoftKeyboard/AnySoftKeyboard/issues/264), [how Swype works](http://www.krishnabharadwaj.info/how-swype-works/) and a [implementation of Swype written on C++](https://gist.github.com/krisys/71acdef7a33ed40bd586)

**Comment by Maccer1** [comment]
> 
> 
> Why did you close this, @Maccer1? I'd love to see glide / swipe on this board

See [here](https://github.com/klausw/hackerskeyboard/wiki/FrequentlyAskedQuestions#please-add-swipe--glide--gesture-typing). I'm afraid it won't happen.
