### ISSUE TITLE
 Color of secondary symbols

### ISSUE THREAD

**Issue by dayfuaim** [klausw/hackerskeyboard#677]
I use the ICS scheme. Everything's all right.
But in last update color of secondary symbols had been changed (see screenshot).
![screenshot_20181120-134308](https://user-images.githubusercontent.com/1274699/48768976-8cd3b100-eccb-11e8-8fbd-72e8ec438a43.png)

This is visually noisy because these two colors are very similar. Also typing speed decreases because of this.
Please change color of secondary symbols back or at least make it darker.

**Comment by klausw** [comment]
I've added an additional "ICS (dark hints)" theme that matches the previous version with black hint letters. I'll keep the default with bright hints for legibility.

This is available in Alpha 1.40.5: https://github.com/klausw/hackerskeyboard/releases

**Comment by dayfuaim** [comment]
Thank you so much!
That's what I needed. :)
BTW Material themes are also very good.

**Comment by klausw** [comment]
Thanks to @PorygonZRocks for the Material themes :-)
