### ISSUE TITLE
Permanent notification missing in 1.40.1

### ISSUE THREAD

**Issue by klausw** [klausw/hackerskeyboard#678]
This is likely due to the switch to target API level 26, the [notifications API page](https://developer.android.com/guide/topics/ui/notifiers/notifications) mentions that a channel and icon is now required.

(reported via email)

**Comment by klausw** [comment]
This should be fixed by commit 6ec1f005c94b58f92ea92d470a27d5ce8cf009ae which is included in the current alpha 1.40.3.

**Comment by evilvertigo** [comment]
My android phone is missing the permanent notification icon that used to force the keyboard to appear...I rely heavily on this app..any ideas how to fix this?

**Comment by klausw** [comment]
Please try the 1.40.4 alpha, it's fixed in that. You can opt in at
https://play.google.com/apps/testing/org.pocketworkstation.pckeyboard , or
wait a day or two for that to be released.

**Comment by evilvertigo** [comment]
Ok..I opted in to the alpha just waiting for the update I guess

**Comment by evilvertigo** [comment]
So a heads uo with the alpha, if you hit ckear notifications, the icon disappears, you then must open hackers settings, unclick permanent notification, the reclick it to get it it reappear

**Comment by klausw** [comment]
Oops. Please try v1.40.5, the disappearing notification should be fixed in that.
