### ISSUE TITLE
Popup mini-keyboard contents not being displayed

### ISSUE THREAD

**Issue by lazarusllong** [klausw/hackerskeyboard#681]
Although one can select the popup mini-keyboard content if one knows the relative key position, the popup itself stoped being displayed since the latest Play Store update (1.40.1).

**Comment by lazarusllong** [comment]
To clarify, this is happening in the 5th row of 5-row layout keyboards (tested with en_US and pt_PT layouts).

**Comment by raumalainen** [comment]
This is real nuisance. Sometimes the top line long-press characters can not be seen at all. Sometimes half of them are behind the normal keyboard,sometimes you can see only part of the second line popup keys.
This behaviour appeared possibly this week (18-22.11.2018). 
I re-installed the app with no help.

**Comment by James868** [comment]
I can confirm that this issue is still exist in the latest version.

**Comment by klausw** [comment]
Please see issue #686. The history here is a bit complicated, and Android P is unfortunately expected to be broken. Older Android versions should work with alpha 1.40.4m but please follow up on that bug if applicable.
