### ISSUE TITLE
Additional letters on finger

### ISSUE THREAD

**Issue by jnuesch** [klausw/hackerskeyboard#685]
The additional signs are all displayed in the keyboard part. So for the top row, there is no space and the additional signs are under the finger which types. In the 4 row configuration this is especially a problem as the numbers are additional signs in the top row. 
I have the impression it started with 1.40.1. I'm on lineageos 15.1, so Android 8.1

**Comment by klausw** [comment]
Please see issue https://github.com/klausw/hackerskeyboard/issues/686 for current status of the popup issues.
