### ISSUE TITLE
Regression: Broken Transparent Keyboard?

### ISSUE THREAD

**Issue by TPS** [klausw/hackerskeyboard#689]
@KlausW Regressions w/ v1.40.5ɑ/β:
- [ ] No longer transparent, whatever the drawing mode
- [ ] <kbd>⇥ Tab</kbd>, both <kbd>⇧ Shift</kbd>s, <kbd>⓿ Settings</kbd>, <kbd>⌫ Backspace</kbd>, <kbd>⏎ Enter</kbd>, <kbd>🎙 Microphone</kbd>, & <kbd>⎵ Space</kbd> are black, while all other keys have always been white
----
- [ ] Bonus bug: Did you know that "Voice Input: off" AFAICT has always acted the same as "Voice Input: On symbols keyboard"?

Thanks very much for all the recent updates! 🙇

**Comment by klausw** [comment]
Should be fixed in v1.40.6 alpha. I've restored the original recoloring behavior for this keyboard, and added a separate "invert symbols" mode for the light-background themes.

**Comment by TPS** [comment]
@KlausW Thanks very much!  It looks just as it used to! 🙇
