### ISSUE TITLE
Tab Key Not Working.

### ISSUE THREAD

**Issue by Bulk-204** [klausw/hackerskeyboard#693]
Thanks klausw for giving us one of the best keyboard.
But tab key(indentation key) isn't working.
It's working reverse.
I hope, you'll fix this soon.
Again,thank you.

**Comment by klausw** [comment]
Can you be more specific about what's happening? Note that Tab key isn't an "indentation key" as such. It just sends a TAB key even to the application which then interprets it. It's common for Tab to switch to the next input field, and the order of input fields is up to the app.

**Comment by Bulk-204** [comment]
Ok,
I screen record  it for you.
[Screen Video](https://res.cloudinary.com/tarek/video/upload/v1543345877/20181128_010354.mp4)
And trust me,this is not spam.
If you saw this video,then you'll get my issue.

**Comment by klausw** [comment]
Sorry, I don't think I can help with this. Like I said earlier, the Tab key just sends a keycode to the application, and in this case the text editor seems to be ignoring it. Try a different text editor? For example, in the Google Docs editor app, the Tab key works just fine for me for indentation.

**Comment by TPS** [comment]
@Bulk-204 What app are you using?  If I'm seeing your cues correctly, it looks like https://play.google.com/store/apps/details?id=com.simplemobiletools.notes or https://play.google.com/store/apps/details?id=com.simplemobiletools.notes.pro .  If so, I can confirm I've the same behavior, *no matter what my keyboard*, & so you should direct your RFE to, e.g., @tibbi, who'd hafta @ least accept the PR (if you were to implement this…  hint, hint).

**Comment by Bulk-204** [comment]
@TPS I've seen this problem every where.
Every Text Field.
And i used QuickEdit Pro in this video.

**Comment by Bulk-204** [comment]
@klausw This Tab Key Decrease Indent For Me.

**Comment by klausw** [comment]
Please see https://github.com/klausw/hackerskeyboard/wiki/FrequentlyAskedQuestions#some-keys-dont-work-for-example-ctrl-cctrl-v-for-cutpaste  :

> Support for the extra keys varies by application. The keyboard just sends key events, and the application receiving the key events is responsible for acting on them, and typically applications ignore unknown or unexpected key events, or (in unfortunate cases) misinterpret the keystrokes to launch menu shortcuts or similar.
> 
> If possible, try attaching a USB or Bluetooth keyboard to your Android device to see if the corresponding keys work with a real hardware keyboard. If that also doesn't work, it'll most likely require a change to the application before a soft keyboard such as this one can support them. If it works with a real keyboard but not with the Hacker's Keyboard application, please file a bug.
> 
> Developers: see KeyboardSupportInApplications for more information.
>
