### ISSUE TITLE
Feature Request: Support Samsung DeX

### ISSUE THREAD

**Issue by arno01** [klausw/hackerskeyboard#697]
It looks like I cannot enable the Hacker's Keyboard while I'm in DeX.

**Comment by TPS** [comment]
Are you on ≥Oreo?  If not, that's a Dex limitation.…

https://www.samsung.com/global/galaxy/apps/samsung-dex/

**Comment by arno01** [comment]
I am on Android 8.1.0 (Oreo).
Then I wonder why can't I enable the Hacker's Keyboard when in DeX mode..

![screenshot_20181206-184815_settings](https://user-images.githubusercontent.com/3791945/49602040-c7a23e00-f987-11e8-8399-ae5890f53189.jpg)

![screenshot_20181206-184836_settings](https://user-images.githubusercontent.com/3791945/49602034-c3762080-f987-11e8-8b3b-cbf846a8ea8d.jpg)

**Comment by klausw** [comment]
Sorry, I don't have a Samsung device and don't know anything about Dex, so I can't help with this. Do any third-party keyboards work? For example, voice typing is also showing as disabled.

**Comment by arno01** [comment]
Asking Samsung Support, will come back with the feedback.

**Comment by arno01** [comment]
In DeX we can only use the "Samsung Keyboard":
![20181212_174046](https://user-images.githubusercontent.com/3791945/49884479-3a526400-fe35-11e8-8e0e-64ac05368a60.jpg)
