### ISSUE TITLE
Can't choose other ime

### ISSUE THREAD

**Issue by Cirooo** [klausw/hackerskeyboard#713]
When using hacker's keyboard, there's no way to pop-up the ime choose dialog. Unlike the others which I can long press space key. 
In Android 8, no current keyboard setting, means I must disable hacker's first.

**Comment by klausw** [comment]
There should be a keyboard switch icon in the softkey system area below the
keyboard:

**Comment by klausw** [comment]
There should be a keyboard switch icon in the softkey system area below the
keyboard:
![screenshot](https://user-images.githubusercontent.com/1392351/51164803-fe0a8d00-1852-11e9-981b-afae571f8701.png)

**Comment by Cirooo** [comment]
What?!  Sorry, I just found the place, it's the first time I notice this tiny icon.
