### ISSUE TITLE
Support for Unicode 12.0 and Emoji

### ISSUE THREAD

**Issue by Industrial** [klausw/hackerskeyboard#730]
This, for me, is the only thing missing from hacker's keyboard. Emoji. I don't need any text completion or spelling correction etc. I can type the words that I wan't and I can correct my mistakes.

I want to type more then words. I want to type the things that ALL chat platforms support nowadays. I can't do it with Hacker's Keyboard.

Please add this.

**Comment by TPS** [comment]
Duplicates #376, among many others.

**Comment by Industrial** [comment]
Maybe they keep coming because no-one has answered that one yet. It's just people agreeing on that it's needed functionality.
