### ISSUE TITLE
Number Row Popup Selection Impossible on Certain Input Type

### ISSUE THREAD

**Issue by Yowlen** [klausw/hackerskeyboard#734]
For the `type=TEXT|AUTO_COMPLETE|NO_SUGGESTIONS` input type, it's impossible to select anything from the top number row. This mode is used by Nova Launcher when editing shortcut labels, if you need an easy place to verify/test.

In case it matters, I'm using the compact 5-row layout and running Android 7.0.

**Comment by klausw** [comment]
I think this is the known issue https://github.com/klausw/hackerskeyboard/issues/686 - I don't have a fix for that yet.

**Comment by Yowlen** [comment]
Oh, I gotcha. I wasn't aware everything was being tracked in one issue. I'll close this and add to that one instead.
