### ISSUE TITLE
At when version for F-DROID ?

### ISSUE THREAD

**Issue by borrougagnou** [klausw/hackerskeyboard#746]
Hello,

Huawei stop soon to use PlayStore (because google, because USA, ...)
so, why don't add your apk on other store like f-droid ?

Regards.

**Comment by TPS** [comment]
Umm, it's ___already___ there @ https://f-droid.org/app/org.pocketworkstation.pckeyboard .…

**Comment by borrougagnou** [comment]
But why klausw didn't mention that
+
why the version isn't up to date ?

**Comment by TPS** [comment]
[He doesn't officially _support_ F-Droid](https://github.com/klausw/hackerskeyboard/issues/699#issuecomment-446057260), but it's built directly from source here, so precisely same version as GPlay (even right now)

**Comment by borrougagnou** [comment]
Okay but I think its the time to add fdroid into the readme + add the latest version of hackerskeyboard into rhe f-droid repo

**Comment by TPS** [comment]
What version did you want in F-Droid⁈

As for the other, change issue title.

**Comment by borrougagnou** [comment]
Ha ! my bad sorry...
I didn't found 1.41.1 alpha version...

I can close this post
