### ISSUE TITLE
Using Hackers Keyboard without google services?

### ISSUE THREAD

**Issue by therealrobster** [klausw/hackerskeyboard#759]
Hi,

I am running LineageOS and don't have any google services installed.

How can we get access to the APK so we can install without Google spying on us and using the play store?

Thanks so much.

**Comment by TPS** [comment]
This is available any number of places that aren't Google-related, e.g.:
- https://github.com/klausw/hackerskeyboard/releases
- https://f-droid.org/en/packages/org.pocketworkstation.pckeyboard/
- https://www.apkmirror.com/apk/klaus-weidner/hackers-keyboard/

**Comment by therealrobster** [comment]
Briliant!  I did search f droid but i must have typed incorrectly.  Really appreciate your answer.

**Comment by TPS** [comment]
Glad to help.  Close this issue FTW? 🙇🏾‍♂️

**Comment by therealrobster** [comment]
definitely.  Thank you
