### ISSUE TITLE
What information is collected, and how is it used?

### ISSUE THREAD

**Issue by Vortetty** [klausw/hackerskeyboard#782]
@klausw i know that typing data will be collected for autocomplete, etc. however how is this information handled? is it just stored locally, or do you send usage statistics, and how is possibly sensitive info handled as i can't seem to find a privacy policy.

**Comment by Camiga** [comment]
The permissions list for Hacker's Keyboard doesn't include internet access, so usage statistics can not be sent by the main program. Typing data should just be stored locally.

**Comment by danieldjewell** [comment]
In a quick review of the code, I don't see anything that really tracks anything ... except for the user specific dictionary which is saved on the device.

**Comment by Vortetty** [comment]
ok!
