### ISSUE TITLE
Keyboard icon in notification area disappeared

### ISSUE THREAD

**Issue by evilvertigo** [klausw/hackerskeyboard#783]
Using the hackers keyboard app on a Samsung S10. Using version v1.41.1official, keyboard icon in the notification area has disappeared and now all of a sudden i have crosshairs on my keyboard everywhere i touch it..need the icon for my work app, and the crosshairs are very annoying

**Comment by TPS** [comment]
You've probably gotta couple of settings flipped the wrong way:
- `Use permanent notification` should be __ON__
- `Debug touch screen position` should be __OFF__

**Comment by evilvertigo** [comment]
Yup both are right, the crosshairs on the keyboatd magically disappeared..but the keyboard icon is still missing

**Comment by eebssk1** [comment]
Notification icon looks missing on android 9.

**Comment by TPS** [comment]
I have it in Android 10.  Did you check settings above?

**Comment by evilvertigo** [comment]
I should have posted on here, soery I forgot to. It is fixed now..think it was corrupted installation..deleted, reinstalled ..fixed

**Comment by eebssk1** [comment]
It works after installing github version...
