### ISSUE TITLE
German PC standard layout: greek µ an € (Euro currency sign) missing

### ISSUE THREAD

**Issue by df7be** [klausw/hackerskeyboard#788]
Hallo Klaus,
vielen Dank für das Hackers Keyboard, es ist wirklich viel besser als die Standard-Tastaturen unter Android.
Da mein Englisch nicht so gut ist, hier meine Beschreibung auf deutsch:
Ich benötige für Internet-Recherchen oft das Mü, auf jeder PC-Tastatur unter AltGr+M aufzurufen).
µ steht im SI-System für Einheiten als "millionstel einer Einheit wie µ Farad für Kondensatoren.
Einige IC's von Toshiba beginnen in der Typenbezeichnung mit z.B. µA7805, µPC... .
Und wir bezahlen in €.

MNI TNX de DF7BE, Wilfried

**Comment by klausw** [comment]
https://github.com/klausw/hackerskeyboard/blob/master/app/src/main/res/values-de/donottranslate-altchars.xml

€ ist auf der "e"-Taste,  µ auf der "m"-Taste, lange gedrückt halten und im popup-Menü auswählen.
