### ISSUE TITLE
In my keyboard, all the keys are not displayed

### ISSUE THREAD

**Issue by Vinayakweb** [klausw/hackerskeyboard#794]
`Hey,` in my keyboard all keys are not displayed there is `function key,control key,arrows, etc.`are not in my keyboard.

- **Please help me**
![IMG_20200321_153057](https://user-images.githubusercontent.com/62464381/77224178-0cf07c00-6b89-11ea-95a6-9b647d13e870.jpg)

**Comment by Vinayakweb** [comment]
Plz help mr

**Comment by TPS** [comment]
Settings (that round weird button on lower left) → Keyboard mode, {portrait, landscape} (3rd & 4th setting)→ Full 5-row  layout  (_or_ 5-row compact layout, but then settings key's moved to Fn page)

**Comment by Vinayakweb** [comment]
**Thanks **
