### ISSUE TITLE
Hacker's Keyboard  on  Laptop  --  Thinkpad x380 Yoga

### ISSUE THREAD

**Issue by warppower** [klausw/hackerskeyboard#811]
Klaus,

I can't find words how awesome the HK is on Android,
really comprehensive solution.

I would like it implemented as virtual pop-up keyboard on the laptop as well!
Can you point me to the steps nedded to be taken to realize this fully & completely.
Compile, etc...

Or can you do this?

**Comment by warppower** [comment]
Have seen now Win version available.
What about Linux..
Using Qubes.

**Comment by TPS** [comment]
> Have seen now Win version available.
@warppower Could you link that here?

**Comment by LinuxRunsTheWorld** [comment]
> Have seen now Win version available.
> What about Linux..
> Using Qubes.

+1 for a Linux version.

**Comment by birdofprey** [comment]
> > Have seen now Win version available.
> > What about Linux..
> > Using Qubes.
> 
> +1 for a Linux version.

+1 for a Linux version.

**Comment by klausw** [comment]
Sorry, this is purely an Android application, and as far as I know it would pretty much need a rewrite to work on a different OS. You're welcome to extract parts from it that would be useful, i.e. keyboard maps, since it's open source, but I think that would need to be a different project, sorry.
