### ISSUE TITLE
I have two issues, Keyboard vibrations and portrait mode keys

### ISSUE THREAD

**Issue by W1ll1am04** [klausw/hackerskeyboard#820]
Can i enable keyboard vibrations? Like when i press a key and i vibrates. 

And have the full keys in portrait mode?

i could'nt find it in settings.
Thanks.

**Comment by klausw** [comment]
Are you looking in the right settings menu? It should say "Settings for Hacker's Keyboard", you can access it from the "Settings" button from the keyboard's main application (the icon it adds to the launcher).

Vibration is in settings > Key feedback settings, with configurable duration. This of course require that you have hardware support for that, not all phones do.

For full keys in portrait, that's at the top "Keyboard view settings" section, "Keyboard mode, portrait".
