### ISSUE TITLE
Disabling all animations for usage in eink devices

### ISSUE THREAD

**Issue by patientx** [klausw/hackerskeyboard#821]
Hi there, I am using HK for over two years now across all of my android devices. Recently got an android based eink reader (7.8 inch, octacore 2 gb ram etc) and installed hackers keyboard to it as usual. The device has an a2 mode in which ghosting is reduced (compared to normal mode) a lot but still there is some ghosting to be seen in keyboard typing. Can we entirely disable all animations in the program , maybe a toggle somewhere can be put ? Otherwise this keyboard is great for eink devices as well as normal ones.

**Comment by TPS** [comment]
Best way to do this is across your entire device: https://lifehacker.com/disable-animations-on-android-to-improve-performance-1583554900

**Comment by patientx** [comment]
One of them was on the others were already off , thanks for the tip, the ghosting is non-existant now , keyboard is flawless on the device.
