### ISSUE TITLE
Pop-up key feedback delay issue

### ISSUE THREAD

**Issue by michaelmouton** [klausw/hackerskeyboard#831]
9/10 works as it sould.  However, in "Key feedback settings" if I enable "Pop-up on keypress" and I type really fast, the pop-up icon would sometimes not dissapear (as it should), but it moves from one position to another.  I have this feature disabled because of that.  I really need that feature!  If you could fix this bug it would be awesome!

**Comment by 18iteration** [comment]
Type slower. I will see which option could help, maybe set draw thingy to hardware or the save memory one.

It's sad to see all these issues and the dev not helping.
My keyboard closes because of the tab key every time but seeing all these open cases I suppose a different keyboard is better

**Comment by LinuxRunsTheWorld** [comment]
It's very disappointing, @18iteration, that the developer is no longer interacting with users. Hackers is, by far, the best Android keyboard I've ever used, but now that Klaus isn't responding to--isn't even acknowledging--complaints, I may have to start looking for a replacement. :(

**Comment by michaelmouton** [comment]
It really is a shame.  It's so lightweight, and simply is the best (even with the 100+ unresolved issues).

Gboard and Swiftkey are pure garbage.  They collect your data without consent.  And because they are larger (30+mb), they are much, much slower.

I'll try to get a dev environment set up, and make those damn modifications myself!  I am familiar with programming, I just haven't done much Android developing.

**Comment by LinuxRunsTheWorld** [comment]
You're awesome, @michaelmouton! That would be great.

I was a programmer--on *nix, no less--but am disabled now and, over time, got more and more out of the loop. A couple years ago, I installed Android Studio, thinking, "you know, it's Linux at heart, how hard can this be?" Yeah, well... I was so lost. It's okay, I'm not complaining. I'm grateful to have survived what nearly killed me, and I'll take brain fog and lack of skills any day over its alternative!

If you do get to work on this yourself, I'll be more than happy to alpha- or beta-test anything you come up with. I have a variety of Android devices and versions. Plus I'll be happy to provide feedback, suggestions, whatever.

I just don't understand why Klaus has gone silent. Is he okay? Could he be ill? He produces this AMAZING keyboard that I don't want to abandon....but it looks like he has.

**Comment by michaelmouton** [comment]
Thanks @LinuxRunsTheWorld 

Would be great if @klausw could at least provide us with a basic build guide.  I'm struggling to get Android Studio set up xD

**Comment by 18iteration** [comment]
I dont understand why gmail sends me different issuw texts than github but
here's the text:

"Thanks @LinuxRunsTheWorld

Would be great if @klausw could at least provide us with a basic build
guide. I'm struggling to get Android Studio set up xD"

No klausw absolutely doesn't have to provide jack sh.t
Especially something as basic as setting up android studio. If you can't
get that done then you have other problems.

Klausw was nice enough to leave the source code open. That's enough.

michaelmouton <notifications@github.com> schrieb am Di., 8. Dez. 2020,
08:57:

**Comment by michaelmouton** [comment]
I sent that comment, and then deleted because I found out that he actually DID provide us with a build guide here...

https://github.com/klausw/hackerskeyboard/wiki/BuildingFromSource

After reading that I got Android Studio set up.  Will be toying around some more later.

My experience lies with NASM, Python, and HTML.  I've never done anything as advanced as this.  Gimme a break, I'm offering my contributions free of charge!

Yes, I am absolutely grateful that he did actually give us code to work with!

**Comment by 18iteration** [comment]
Nobody is asking you to contribute. Period.

michaelmouton <notifications@github.com> schrieb am Di., 8. Dez. 2020,
10:25:

**Comment by michaelmouton** [comment]
Comeback of the century.

I'm trying to help.  Believe it or not, the non-removable TAB key also annoys the hell out of me (the issue you listed).  That's one of the main reasons I actually WANT to contribute.  I never said anyone asked me, or wanted me to contribute.

**Comment by michaelmouton** [comment]
At least @LinuxRunsTheWorld appreciates my help.

**Comment by 18iteration** [comment]
Opened #831

michaelmouton <notifications@github.com> schrieb am Di., 8. Dez. 2020,
13:57:

**Comment by LinuxRunsTheWorld** [comment]
Indeed I do, @michaelmouton. Definitely. Since Klaus has gone into hiding (I do hope he's okay), your interest in this sounds great. Don't worry if it doesn't work out. At least you're trying. :)
