### ISSUE TITLE
How to get rid of this Key (closes keyboard, accidentially often)

### ISSUE THREAD

**Issue by 18iteration** [klausw/hackerskeyboard#832]
![Screenshot_20201203-110612__01](https://user-images.githubusercontent.com/45468984/100995268-d82a2680-3557-11eb-9606-950d695b0703.jpg)

I hate that key (Tab key I suppose). I accidentially click on it every time. Due to it, my typing speed decreased greatly.

It's useless to me, how can we get rid of it?

**Comment by TPS** [comment]
It looks like you're using the 4-row layout.  Have you tried either of the 5-row layouts?  They don't *re*move any keys, just *move* them, but that might be useful enough to you.

**Comment by abmabmabm** [comment]
في الخميس، ٣ ديسمبر ٢٠٢٠ ١٢:٣٦ م TPS <notifications@github.com> كتب:

**Comment by LinuxRunsTheWorld** [comment]
I agree with @TPS, try using a 5 (or more) row layout. I normally use 5, and don't have issues with the tab key.

**Comment by 18iteration** [comment]
I cant work fast with so many keys that I dont even need. I just want to get rid of the tab key
