### ISSUE TITLE
Shift button

### ISSUE THREAD

**Issue by simplySmart** [klausw/hackerskeyboard#851]
Plese add a shift key !!😁😁
It will be more helpful

**Comment by TPS** [comment]
@simplySmart Umm, _huh_?!  _Every_ configuration of this KB has a <kbd>Shift</kbd> that looks somewhat like <kbd>⇪</kbd>.

**Comment by simplySmart** [comment]
Not that key the key that used in combination for eg. ctrl+alt+shift. Got
it!!

**Comment by TPS** [comment]
That's the same key....  Really not understating the confusion.

**Comment by simplySmart** [comment]
I am still having confusion please send a video 😐..
Thanka for your attention

**Comment by simplySmart** [comment]
I got it! 😁😁😀 I tried and it worked ...
Thank you so much ❤️😘😘
