### ISSUE TITLE
Equal sign hidden

### ISSUE THREAD

**Issue by ShalokShalom** [klausw/hackerskeyboard#859]
On the 4 row setting, it seems to take 3 different presses on different buttons, to make one of the most frequent signs: =

I see tons of lesser used ones on the pop up menu of the period, like & and @

I suggest to make the equals sign accessible in that menu, instead of the & or @ sign.

For programmers specifically, is this highly important.

How can I code without the equals key?

**Comment by TPS** [comment]
For coding, it doesn't really make sense to use anything else _besides_ the full 5-row layout, which has 1-tap access to almost every standard key.  Try that from HK's settings.

**Comment by ShalokShalom** [comment]
The 4 row layout provides all, other than the equals key.

Why adding clutter, if it can be done simple.

**Comment by KevinBlue18** [comment]
@ShalokShalom The 4-row layout is based on the default Android Gingerbread keyboard. The developer made this keyboard with the intention using the 5-row layout. Which is why the developer didn't modify the 4-row layout.
