### ISSUE TITLE
Keyboard prevents OCBC Singapore Bank app from running

### ISSUE THREAD

**Issue by xobs** [klausw/hackerskeyboard#898]
This is more of an advisory bug report than anything, just so that it's documented somewhere.

There are at least four "blacklisted" programs that the OCBC Singapore banking app looks for. For some reason, "Hacker's Keyboard" is on this list. If this keyboard is installed on a device, the banking program will refuse to run and say the program has been tampered with.

Unfortunately the short-term solution is to uninstall Hacker's Keyboard.

I'm unsure how it determines what programs are installed, or whether it's worth it to switch. I'm waiting to see if I can get more information from OCBC Singapore.

**Comment by TPS** [comment]
They probably won't consider beyond the name, similar to [how Process Hacker needed to change its name](https://github.com/winsiderss/systeminformer) to avoid M$ blocklists.
