### ISSUE TITLE
It's been three months and still no word, [what] I don't deserve it?
I know you got my last two letters,...

### ISSUE THREAD

**Issue by TheKernelNewbie** [klausw/hackerskeyboard#904]
> How to switch between soft and hard keyboard buffer?

> I have used this before maybe it is only in a specific build. If you can point me to the build that works I will move off of this official build page.

Closed - Stale Issue.

_Originally posted by @TheKernelNewbie in https://github.com/klausw/hackerskeyboard/issues/894#issuecomment-1234198321_

**Comment by TheKernelNewbie** [comment]
**Is it any of the 399 forks?**

**Comment by Etanarvazac** [comment]
@TheKernelNewbie Remember this is an old project that isn't updated regularly anymore. So 3+ month wait is to be expected.

**Comment by Etanarvazac** [comment]
@TheKernelNewbie Could this be what you are seeting in the keyboard settings:
![Screenshot_20220901-125410_Hacker's Keyboard.jpg](https://user-images.githubusercontent.com/55290878/187970065-1732149d-4d90-49c2-bbc0-cbfdc421b31a.jpg)

**Comment by klausw** [comment]
@TheKernelNewbie - don't spam repositories with silly subject changes and messing around with issue status. You'll get blocked if you do this again.

@Etanarvazac thanks for helping out!
