### ISSUE TITLE
Delete words from dictionary?

### ISSUE THREAD

**Issue by Zemyla** [klausw/hackerskeyboard#931]
I'm not the best at typing, and I've made many typos that have made it into the personal dictionary even though I've never explicitly added them. "Thatm" and "thatps" in particular bother me. Can I delete them and prevent them from being added again?

**Comment by TPS** [comment]
These are in your Android personal dictionary, not HK settings, & are meant to be used across any keyboards you may use.

Location to edit it varies per Android version & device manufacturer, but is generally located @ Settings » System » Keyboard » Personal Dictionary

**Comment by Zemyla** [comment]
Okay, that did it. Thanks!
